import pandas as pd
import numpy as np
from datetime import datetime, timedelta

print("=" * 60)
print("🧲  EM HUNTING MACHINE — SIMULATOR")
print(f"Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print("=" * 60)

# Load mission plan
plan    = pd.read_csv("intercept_plan.csv").iloc[0]
windows = pd.read_csv("launch_windows.csv").iloc[0]

# ==========================================
# ASTEROID PROPERTIES
# ==========================================

asteroid_name     = plan["target"]
asteroid_mass_kg  = plan["asteroid_mass_kg"]
asteroid_size_km  = 0.874
asteroid_speed    = 23.08  # km/s from our data
em_score          = 95     # M-type iron rich

print(f"\n🎯 Target: {asteroid_name}")
print(f"   Mass:     {asteroid_mass_kg:.2e} kg")
print(f"   Size:     {asteroid_size_km} km")
print(f"   Speed:    {asteroid_speed} km/s")
print(f"   EM Score: {em_score}/100")

# ==========================================
# EM MACHINE PROPERTIES
# ==========================================

print("\n" + "=" * 60)
print("⚡  EM MACHINE SPECIFICATIONS")
print("=" * 60)

# Solar power farm in space
SOLAR_PANEL_AREA_M2   = 143_571_000_000  # m²
SOLAR_INTENSITY       = 1.4              # kW per m²
SOLAR_EFFICIENCY      = 0.30             # 30% panel efficiency
EM_POWER_MW           = (SOLAR_PANEL_AREA_M2 * SOLAR_INTENSITY * 
                         SOLAR_EFFICIENCY) / 1000      # Megawatts
EM_FIELD_RADIUS_KM = 50                        # field reach
EM_EFFICIENCY      = em_score / 100            # 0.95 for M-type

# Force generated by EM field on iron asteroid
# F = efficiency * power * 1000000 / speed_of_light
SPEED_OF_LIGHT     = 300000  # km/s
# Multiple EM machines surrounding asteroid
NUM_EM_MACHINES  = 1000
em_force_newtons = (EM_EFFICIENCY * EM_POWER_MW * 1e6 / 
                   SPEED_OF_LIGHT) * NUM_EM_MACHINES

print(f"Power output:      {EM_POWER_MW:.0f} Megawatts")
print(f"Field radius:      {EM_FIELD_RADIUS_KM} km")
print(f"EM efficiency:     {EM_EFFICIENCY*100:.0f}%")
print(f"Force generated:   {em_force_newtons:.2e} Newtons")

# ==========================================
# DECELERATION SIMULATION
# ==========================================

print("\n" + "=" * 60)
print("🔬  DECELERATION SIMULATION")
print("=" * 60)

# Physics: F = ma → a = F/m
deceleration = em_force_newtons / asteroid_mass_kg  # m/s²
deceleration_km_s2 = deceleration / 1000

print(f"Deceleration rate: {deceleration:.6f} m/s²")
print(f"                   {deceleration_km_s2:.8f} km/s²")

# Simulate deceleration over time
current_speed = asteroid_speed  # km/s
target_speed  = 0.1             # km/s — nearly stopped
time_days     = 0
TIME_STEP     = 1               # 1 day per step

print(f"\nStarting speed:  {current_speed} km/s")
print(f"Target speed:    {target_speed} km/s")
print(f"\nSimulating deceleration...\n")

speed_log = []

while current_speed > target_speed:
    seconds_per_day = 86400
    speed_reduction = deceleration_km_s2 * seconds_per_day
    current_speed   = max(current_speed - speed_reduction, target_speed)
    time_days      += TIME_STEP

    speed_log.append({
        "day":       time_days,
        "speed":     round(current_speed, 4),
        "reduction": round(speed_reduction, 6)
    })

    if time_days % 50 == 0 or current_speed <= target_speed:
        print(f"Day {time_days:4d} → Speed: {current_speed:.4f} km/s")

    if time_days > 10000:
        print("Taking too long — EM power needs increase!")
        break

# ==========================================
# CAPTURE ANALYSIS
# ==========================================

print("\n" + "=" * 60)
print("🪐  CAPTURE ANALYSIS")
print("=" * 60)

capture_date = datetime(2027, 6, 19) + timedelta(days=time_days)

print(f"Time to slow asteroid:  {time_days} days ({time_days/365:.1f} years)")
print(f"Capture date:           {capture_date.strftime('%Y-%m-%d')}")
print(f"Final speed:            {current_speed} km/s")
print(f"Status:                 {'✅ CAPTURED!' if current_speed <= target_speed else '❌ Failed'}")

# ==========================================
# MINING VALUE
# ==========================================

print("\n" + "=" * 60)
print("💰  MINING VALUE ESTIMATION")
print("=" * 60)

iron_mass     = asteroid_mass_kg * 0.80
nickel_mass   = asteroid_mass_kg * 0.15
platinum_mass = asteroid_mass_kg * 0.01
gold_mass     = asteroid_mass_kg * 0.005

iron_value     = iron_mass     * 0.10
nickel_value   = nickel_mass   * 14
platinum_value = platinum_mass * 31000
gold_value     = gold_mass     * 60000

total_value = iron_value + nickel_value + platinum_value + gold_value

print(f"Iron:      {iron_mass:.2e} kg → ${iron_value:.2e}")
print(f"Nickel:    {nickel_mass:.2e} kg → ${nickel_value:.2e}")
print(f"Platinum:  {platinum_mass:.2e} kg → ${platinum_value:.2e}")
print(f"Gold:      {gold_mass:.2e} kg → ${gold_value:.2e}")
print(f"\n💎 TOTAL VALUE: ${total_value:.2e}")
print(f"             = ${total_value/1e12:.1f} TRILLION")
print(f"             = ₹{total_value*83/1e15:.1f} QUADRILLION")

# ==========================================
# MISSION SUMMARY
# ==========================================

print("\n" + "=" * 60)
print("📋  COMPLETE MISSION SUMMARY")
print("=" * 60)

print(f"""
Target:          {asteroid_name}
Launch date:     March 18 2027
Arrival date:    June 19 2027
Travel time:     92 days

EM Machine:
  Power:         {EM_POWER_MW:.0f} Megawatts
  Field radius:  {EM_FIELD_RADIUS_KM} km
  Efficiency:    {EM_EFFICIENCY*100:.0f}%

Deceleration:
  Start speed:   {asteroid_speed} km/s
  Time to stop:  {time_days} days
  Capture date:  {capture_date.strftime('%Y-%m-%d')}

Mining value:    ${total_value/1e12:.1f} TRILLION
""")

# Save simulation
sim_log = pd.DataFrame(speed_log)
sim_log.to_csv("em_simulation.csv", index=False)
print("✅ Simulation saved to em_simulation.csv")
print("=" * 60)